import './globals.css'
import { ThemeProvider } from "./../components/providers/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import { cn } from '@/lib/utils'
// import type { Metadata } from 'next'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang='fa'>
        <body className={cn(
          "bg-white dark:bg-[#313338]"
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            storageKey='discord-theme'
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
